/*Módulo 1: Criação das Tabelas
Comece criando as tabelas que serão usadas no projeto.

Script 1: Estrutura do Banco
*/


-- Criação da tabela de funcionários
CREATE TABLE FUNCIONARIOS (
    ID_FUNCIONARIO NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    CPF VARCHAR2(11) UNIQUE,
    DATA_ADMISSAO DATE,
    CARGO VARCHAR2(50),
    SALARIO_BASE NUMBER(10, 2)
);

-- Criação da tabela de salários
CREATE TABLE SALARIOS (
    ID_SALARIO NUMBER PRIMARY KEY,
    ID_FUNCIONARIO NUMBER,
    VALOR_PAGO NUMBER(10, 2),
    DATA_PAGAMENTO DATE,
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
);

-- Tabela de histórico de pagamentos
CREATE TABLE HISTORICO_PAGAMENTOS (
    ID_HISTORICO NUMBER PRIMARY KEY,
    ID_FUNCIONARIO NUMBER,
    VALOR NUMBER(10, 2),
    MES_REFERENCIA VARCHAR2(10),
    DATA_REGISTRO DATE,
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO)
);

-- Tabela de auditoria de pagamentos
CREATE TABLE AUDITORIA_PAGAMENTOS (
    ID_LOG NUMBER PRIMARY KEY,
    OPERACAO VARCHAR2(20),
    ID_FUNCIONARIO NUMBER,
    VALOR_ANTIGO NUMBER(10, 2),
    VALOR_NOVO NUMBER(10, 2),
    DATA_HORA TIMESTAMP
);

-- Tabela de logs de erro
CREATE TABLE LOG_ERROS (
    ID_LOG NUMBER PRIMARY KEY,
    DESCRICAO_ERRO VARCHAR2(4000),
    DATA_OCORRENCIA TIMESTAMP
);
