/*Package
Um package encapsula procedures, functions e variáveis, promovendo organização e reutilização do código.

Package Specification
Define os métodos disponíveis no pacote.*/

CREATE OR REPLACE PACKAGE PKG_GESTAO_FUNCIONARIOS AS 
	PROCEDURE INSERIR_FUNCIONARIO(
		p_ID_FUNCIONARIO IN NUMBER,
		p_NOME IN VARCHAR2,
		p_CPF IN VARCHAR2,
		p_DATA_ADMISSAO IN DATE,
		p_CARGO IN VARCHAR2,
		p_SALARIO_BASE IN NUMBER
	);

	
	FUNCTION CONSULTAR_FUNCIONARIO(p_ID_FUNCIONARIO IN NUMBER)
		RETURN VARCHAR2;
	
	
	PROCEDURE REGISTRAR_ERRO(p_DESCRICAO_ERRO IN VARCHAR2);
	
END PKG_GESTAO_FUNCIONARIOS;


/*Package Body
Implementa os métodos declarados no pacote.*/
CREATE OR REPLACE PACKAGE BODY TP.PKG_GESTAO_FUNCIONARIOS AS 
	PROCEDURE INSERIR_FUNCIONARIO(
		p_ID_FUNCIONARIO IN NUMBER,
		p_NOME IN VARCHAR2,
		p_CPF IN VARCHAR2,
		p_DATA_ADMISSAO IN DATE,
		p_CARGO IN VARCHAR2,
		p_SALARIO_BASE IN NUMBER
	) IS 
	BEGIN 
		INSERT INTO FUNCIONARIOS (ID_FUNCIONARIO, NOME, CPF, DATA_ADMISSAO, CARGO, SALARIO_BASE)
		VALUES (p_ID_FUNCIONARIO, p_NOME, p_CPF, p_DATA_ADMISSAO, p_CARGO, p_SALARIO_BASE);
		COMMIT;
	END INSERIR_FUNCIONARIO;

	FUNCTION CONSULTAR_FUNCIONARIO(p_ID_FUNCIONARIO IN NUMBER)
		RETURN VARCHAR2 IS
		v_NOME VARCHAR2(100);
	BEGIN
		SELECT NOME INTO v_nome
		FROM FUNCIONARIOS 
		WHERE ID_FUNCIONARIO = p_ID_FUNCIONARIO;
		RETURN v_nome;
	END CONSULTAR_FUNCIONARIO;
	
	
	PROCEDURE REGISTRAR_ERRO(p_DESCRICAO_ERRO IN VARCHAR2) IS
	BEGIN
		INSERT INTO LOG_ERROS (ID_LOG, DESCRICAO_ERRO, DATA_OCORRENCIA)
		VALUES (SEQ_LOG.NEXTVAL, p_DESCRICAO_ERRO, SYSTIMESTAMP);
		COMMIT;
    END REGISTRAR_ERRO;

END PKG_GESTAO_FUNCIONARIOS;	
	
	
	
	