-- Sequence para a tabela FUNCIONARIOS
CREATE SEQUENCE SEQ_FUNCIONARIOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Sequence para a tabela SALARIOS
CREATE SEQUENCE SEQ_SALARIOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Sequence para a tabela HISTORICO_PAGAMENTOS
CREATE SEQUENCE SEQ_HISTORICO_PAGAMENTOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Sequence para a tabela AUDITORIA_PAGAMENTOS
CREATE SEQUENCE SEQ_AUDITORIA_PAGAMENTOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Sequence para a tabela LOG_ERROS
CREATE SEQUENCE SEQ_LOG
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


/*Essas sequences geram os valores únicos automaticamente para as colunas de chave primária (ID_*). Durante as operações de inserção, basta usá-las assim:*/
INSERT INTO FUNCIONARIOS (ID_FUNCIONARIO, NOME, CPF, DATA_ADMISSAO, CARGO, SALARIO_BASE)
VALUES (SEQ_FUNCIONARIOS.NEXTVAL, 'Carlos Almeida', '12312312345', SYSDATE, 'Gerente', 8000);
