CREATE OR REPLACE PROCEDURE TP.INSERIR_FUNCIONARIO (
    p_ID_FUNCIONARIO IN NUMBER,
    p_NOME IN VARCHAR2,
    p_CPF IN VARCHAR2,
    p_DATA_ADMISSAO IN DATE,
    p_CARGO IN VARCHAR2,
    p_SALARIO_BASE IN NUMBER
) AS 
BEGIN
    -- Tenta inserir os dados
    INSERT INTO FUNCIONARIOS(ID_FUNCIONARIO, NOME, CPF, DATA_ADMISSAO, CARGO, SALARIO_BASE)
    VALUES (p_ID_FUNCIONARIO, p_NOME, p_CPF, p_DATA_ADMISSAO, p_CARGO, p_SALARIO_BASE);

    -- Confirma a transação apenas se não houver erros
    COMMIT;
END;