CREATE OR REPLACE FUNCTION CALCULAR_SALARIO_LIQUIDO(
	p_SALARIO_BASE IN NUMBER,
	p_DESCONTOS IN NUMBER
) RETURN NUMBER 
IS
	v_SALARIO_LIQUIDO NUMBER;
BEGIN
	v_SALARIO_LIQUIDO := p_SALARIO_BAE - p_DESCONTOS;
	RETURN v_SALARIO_LIQUIDO;
END CALCULAR_SALARIO_LIQUIDO;
